language: "node_js"
node_js:
 - "node"
install:
 - "npm install gitbook -g"
 - "npm install -g gitbook-cli"
script:
 - "gitbook build"
after_success:
 - "sh deploy.sh"
 env:
  global:
    - secure: "XVjxvdpLxfp2PDh7vhJaqoc6EzjAhddPcbhQOBf/1fNAzcco0InNRVQ6WsPC8X968+JYWL/UJI6+XVRDL8ACfYvchBzLbI1ULBuxGh/7vhix4B7tbP9tRnqKgtiblkrsg/raQDvO20Vny8iRniT8ZUcwI54umHeefBMjZ6z+I3vcI0XKUJOxyIVQCkkQOiFRA6j7thoWvodQKISECFIKq0zdTm8WtEJAfzrthhHYCdFAU1PEV+bOIL3cyzF1xnrs3H6aQYSSly5Hc35Bfl/K0yhayuN/R84Zgu/uKbGX0zZ9fkQte0qq3kYnghqSUnw9vOteDqJTeeZGKiVbppTgeDAn19Xgpla6MR97/FosYOCvbc9Y3hDdTNx3WY2BaPGPYHAA49kMsThVMq6z1rQCPjFWdlbhv3FAYCYqNtotnrPK6Sb43wNJQYoqfsWA4ZGv/jE/qZuv6wJ3iC5uX9a5J6oD85b999F4QlnGwDNRiaUirjybVJo5xATL5tMEC6NdppGmu5Ix1c64texKCLaZOfYUHcFVoUl52qW+N/klnH3s/DPUcRgLR2O+fCTWDuIJRIsu+B2l0RYJ+KGc8IN57Gamfw4H9/pOpxqPLA4EIy5CGts2gg6qYRZegm08DWb4QSonyWCUZtOX0z9F1LRr9FwIB5WSlGKT8dQw4UpZcEk="